; Talkkeeper — custom English installer strings
LangString addOrReinstall ${LANG_ENGLISH} "Add / reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose what to do next, then click Next."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running. Close it, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is still running.$\nClick OK to close it and continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose a maintenance option."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the current install"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep current install (downgrade without uninstall is disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close {{product_name}}. Quit it manually, then retry."
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft Edge WebView2 runtime…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed. Installing an older build is not recommended. Uninstall first if you really need this version."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed. Uninstalling first is recommended. Choose an option and click Next."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for silent install. Use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 install failed. Talkkeeper needs it to run — restart the setup and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed — $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper…"
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 install failed (exit code $1)"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete meetings, models, and local data"
