; Talkkeeper — custom English installer strings
LangString addOrReinstall ${LANG_ENGLISH} "Add / reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose what to do next, then click Next."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running. Close it, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is still running.$\nClick OK to close it and continue."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose a maintenance option."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the current install"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep current install (downgrade without uninstall is disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close {{product_name}}. Quit it manually, then retry."
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft Edge WebView2 runtime…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed. Installing an older build is not recommended. Uninstall first if you really need this version."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed. Uninstalling first is recommended. Choose an option and click Next."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for silent install. Use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 install failed. Talkkeeper needs it to run — restart the setup and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed — $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper…"
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 install failed (exit code $1)"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete meetings, models, and local data"

; --- welcome page ---
LangString tkEyebrow ${LANG_ENGLISH} "TALKKEEPER  /  LOCAL AI MEETINGS"
LangString tkWelcomeTitle ${LANG_ENGLISH} "Meetings stay yours."
LangString tkWelcomeText ${LANG_ENGLISH} "Recording, transcription, speaker labels and summaries on your own PC."
LangString tkBackendsBox ${LANG_ENGLISH} "  ONE INSTALLER, THREE BACKENDS  "
LangString tkBackendsList ${LANG_ENGLISH} "NVIDIA CUDA    |    AMD / Intel / NVIDIA Vulkan    |    CPU fallback"
LangString tkBackendsHint ${LANG_ENGLISH} "Setup picks the right one by itself."
LangString tkNoAccount ${LANG_ENGLISH} "No account. No subscription. No analytics."
LangString tkFooter ${LANG_ENGLISH} "Talkkeeper  ·  local AI meetings"

; --- install location page ---
LangString tkDirHeader ${LANG_ENGLISH} "Install location"
LangString tkDirSub ${LANG_ENGLISH} "Pick a folder — the suggested one is fine"
LangString tkDirIntro ${LANG_ENGLISH} "Talkkeeper will be installed for your Windows user account. You can change the folder below."
LangString tkDirFolder ${LANG_ENGLISH} "FOLDER"
LangString tkDirBrowse ${LANG_ENGLISH} "Browse…"
LangString tkDirBrowseTitle ${LANG_ENGLISH} "Choose the Talkkeeper install folder"
LangString tkDirSpace ${LANG_ENGLISH} "About 810 MB is needed — the app, the models and the graphics libraries. WebView2 adds a little more on first run."
LangString tkDirRuntimes ${LANG_ENGLISH} "After the files are copied, setup quietly adds WebView2, Visual C++ and the CUDA libraries. An NVIDIA card is used on its own when a driver is present."

; --- installing page ---
LangString tkInstallHeader ${LANG_ENGLISH} "Installing Talkkeeper"
LangString tkInstallSub ${LANG_ENGLISH} "Copying files and preparing the local engines…"
LangString tkUpdateHeader ${LANG_ENGLISH} "Updating Talkkeeper"
LangString tkUpdateSub ${LANG_ENGLISH} "Refreshing files and local engines…"
LangString tkUpdaterTitle ${LANG_ENGLISH} "Talkkeeper Updater"
LangString tkUpdaterFooter ${LANG_ENGLISH} "Talkkeeper  ·  updater"
LangString tkCancelUpdate ${LANG_ENGLISH} "Cancel update"
LangString tkProgressCopy ${LANG_ENGLISH} "Copying files and setting up the engines"
LangString tkProgressUpdate ${LANG_ENGLISH} "Updating to version ${VERSION}"
LangString tkPercentDone ${LANG_ENGLISH} "% complete"

; --- finish page ---
LangString tkFinishHeader ${LANG_ENGLISH} "Install complete"
LangString tkFinishSub ${LANG_ENGLISH} "Talkkeeper is ready on this PC."
LangString tkAbortHeader ${LANG_ENGLISH} "Install cancelled"
LangString tkAbortSub ${LANG_ENGLISH} "No changes were finished."
LangString tkFinishTitle ${LANG_ENGLISH} "Talkkeeper is ready."
LangString tkFinishText ${LANG_ENGLISH} "The transcription backend and the local libraries are installed. First launch has a short setup: your name and an audio check."
LangString tkLaunchNow ${LANG_ENGLISH} "Launch Talkkeeper now"
LangString tkFinishLocal ${LANG_ENGLISH} "All data stays on this PC unless you configure a cloud provider yourself."
LangString tkFinishButton ${LANG_ENGLISH} "Finish"

; --- uninstall ---
LangString tkKeyRescued ${LANG_ENGLISH} "Your recordings are encrypted, and the key that opens them was about to be deleted along with the app data.$\r$\n$\r$\nA copy has been saved here:$\r$\n$DOCUMENTS\Talkkeeper-key-backup\keystore.json$\r$\n$\r$\nKeep this file. Without it — and without your password — existing recordings cannot be opened again."
LangString tkKeyWarning ${LANG_ENGLISH} "You are about to delete the app data, and with it the key that encrypts every recording you have made.$\r$\n$\r$\nThe recordings themselves live elsewhere and will stay on disk, but without this key and your password they can never be opened again.$\r$\n$\r$\nA copy of the key will be saved in Documents\Talkkeeper-key-backup.$\r$\n$\r$\nDelete the app data?"
LangString tkKeyKept ${LANG_ENGLISH} "The key could not be copied, so the app data has been left where it is:$\r$\n$INSTDIR\data$\r$\n$\r$\nIt holds keystore.json, without which the recordings cannot be opened. Save it yourself, then delete the folder by hand."
